services:
  - type: web
    name: roulinpost-3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        sync: true
      - key: MAIL_PASSWORD
        sync: true
      - key: FIREBASE_CREDENTIALS_JSON
        sync: true
    # FIXED: Instructs Render to automatically install native OS dependencies
    aptConfig:
      packages:
        - ffmpeg